[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Naviigator"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
permutohedron = "0.2.4"